### ISSUE TITLE
Debian support is broken

### ISSUE THREAD

**Issue by serenabiodec** [personnage/ansible-role-couchdb#1]
apt_repository module does not support 'ppa/name' repo on Debian:

see http://docs.ansible.com/ansible/apt_repository_module.html
#On Ubuntu target: add nginx stable repository from PPA and install its signing key.
#On Debian target: adding PPA is not available, so it will fail immediately.
apt_repository: repo='ppa:nginx/stable'

**Comment by personnage** [comment]
Thanks!
Removed PPA support.
To install latest version on Debian, follow https://cwiki.apache.org/confluence/display/COUCHDB/Debian
